### ISSUE TITLE
MODX Revo Install Script not working + update for REVo 2.3.1

### ISSUE THREAD

**Issue by mikelannen** [evolution-cms/installer#13]
Hello,

I used this script for about a dozen of my EVOLUTION sites and it works perfectly.

I can not however get it to work for any REVOLUTION sites.

Whenever I run the script on a Revolution sites, it sites for a while and then goes to a page not found / 404. I am not sure if this is an issue on my server only or a bug?

Also need an update for MODX REVO 2.3.1. I put one in myself for the script, but I can not get that working either.

Any suggestions?

**Comment by terrybarth** [comment]
Has anyone figured this out? I found it works on a few site, but not for most. I just updated three sites on the host (different accounts). It worked on one, but not the other two.
