### ISSUE TITLE
Temp directory needs trailing slash

### ISSUE THREAD

**Issue by sottwell** [evolution-cms/installer#15]
On some systems the extract will fail because the temp directory needs a trailing slash. Line 133.

**Comment by terrybarth** [comment]
So I have three different sites, all on Hostmonster, all setup at the same time. This worked on one site, but not the other two.  Wouldn't these three have the same requirements?

Will some systems fail if there is always trailing slash on the temp directory?

**Comment by sottwell** [comment]
I don't know, I do know that adding the trailing slash solves the "failed to extract" error on some sites. I haven't used it enough since adding the slash to have it error again.

**Comment by sottwell** [comment]
Apparently it depends on how the server is configured, how it will extract the files from the zip archive.

**Comment by sottwell** [comment]
I suppose it would just be trial-and-error, if it fails with the slash, try again without the slash...

**Comment by terrybarth** [comment]
Agree. I'll have to try it both ways. I have a few more upgrades to do so, I'll see what happens.  Thanks!

**Comment by sottwell** [comment]
I'm also thinking of a try/catch, if it fails, try again the other way.

**Comment by terrybarth** [comment]
Excellent!


  [image: photo]  Terry Barth
Terry Barth Design
 Phone: 612 859 2453
 Email: terrybarth@terrybarth.com
 Website: www.terrybarthdesign.com
    Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by sottwell** [comment]
I'm sorry I'm not making pull requests any more, but I am just using it for Revo install/upgrade now. Full credit given to your original, of course.

Feel free to go to my repository (sottwell/installer) and get the cURL code if you want it.
